server:
  port: 8081
  error:
    include-messages: "always"
spring:
  application:
    name: "MS_TECHNOLOGY"
  devtools:
    add-properties: false
  r2dbc:
    url: ${JDBC_URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  profiles:
    include: null
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ADMIN_ROLES}
          client-id: ${JWT_CLIENT_ID}
jwt:
  json-exp-roles: "/roles"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:8081,http://localhost:8080"